"""Initial migration

Revision ID: 3c0bad4d4d5c
Revises: 
Create Date: 2026-04-26 18:48:53.255241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0bad4d4d5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_content_sha256'), 'documents', ['content_sha256'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('message_id', sa.CHAR(length=32), nullable=False),
    sa.Column('faithfulness', sa.FLOAT(), nullable=True),
    sa.Column('answer_relevancy', sa.FLOAT(), nullable=True),
    sa.Column('context_precision', sa.FLOAT(), nullable=True),
    sa.Column('context_recall', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_results_message_id', 'evaluation_results', ['message_id'], unique=False)
    op.create_index('ix_evaluation_results_id', 'evaluation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evaluation_results_id', table_name='evaluation_results')
    op.drop_index('ix_evaluation_results_message_id', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_rag_configs_user_id'), table_name='rag_configs')
    op.alter_column('rag_configs', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_sha256'), table_name='documents')
    op.alter_column('documents', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'content_sha256')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
